### PR TITLE
Update OpenCL header files.

### PR DESCRIPTION
**Pull request by naibaf7**
The OpenCL header files are outdated at this point. Request to update them.

### CODE REVIEW

**Comment by naibaf7** [comment]
@karlrupp Opinion?

**Comment by karlrupp** [comment]
Thanks, @naibaf7 . Do you happen to know whether the new headers are fully backwards compatible? I think this is the case, but haven't run any tests.

**Comment by naibaf7** [comment]
Not 100% sure, but I had no issues running ViennaCL inside Caffe with these headers. It could maybe pose a problem for people with a very old OpenCL library, I did not test that.
But in the current situation, if a library will load the headers included with ViennaCL instead of system OpenCL headers, there will be errors about missing definitions etc.

**Comment by karlrupp** [comment]
Thanks, @naibaf7 . Your argument with the old headers potentially breaking builds on newer systems is good.

**Pull request merged**
